# Generated by Django 4.1.9 on 2023-07-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('difficulty', models.CharField(max_length=100)),
            ],
        ),
    ]
