# Generated by Django 4.1.9 on 2023-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_totsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='totsubmission',
            name='problem',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
