# Generated by Django 4.1.9 on 2023-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_totsubmission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='totsubmission',
            name='date_of_submission',
            field=models.DateField(default='2023-07-19'),
            preserve_default=False,
        ),
    ]
